name: Blank Workflow
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: test in parallel with build
          run: echo "parallel with build"

        